In [57]:
import pandas as pd

In [58]:
pd.__version__

'3.0.6'

In [59]:
df = pd.read_csv('car_fuel_efficiency_2026.csv')

In [60]:
df.shape

(10000, 11)

In [61]:
df.nunique()

model_year              50
origin                   3
fuel_type                3
drivetrain               3
num_doors                4
engine_displacement    127
num_cylinders            5
horsepower             153
vehicle_weight         176
acceleration            93
fuel_efficiency_mpg    188
dtype: int64

In [62]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [63]:
df[
    df['origin'] == "Asia"
].fuel_efficiency_mpg.max()

np.float64(41.2)

In [64]:
hp_median = df.horsepower.median()
hp_median

np.float64(254.0)

In [74]:
common_hp = df.horsepower.mode()[0]
common_hp

np.float64(252.0)

In [75]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [76]:
df.horsepower = df.horsepower.fillna(common_hp)

In [77]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower               0
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [78]:
new_median = df.horsepower.median()
new_median

np.float64(252.0)

In [79]:
df_asia = df[
    df['origin'] == "Asia"
]

In [80]:
df_asia.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
6,1992,Asia,Gasoline,Front-wheel drive,2,2270,6,250.0,4310,21.7,26.8
8,1997,Asia,Gasoline,Rear-wheel drive,3,2330,6,251.0,4230,19.5,30.9
10,1978,Asia,Gasoline,All-wheel drive,3,2410,6,252.0,4420,19.5,26.8
15,2007,Asia,Diesel,Front-wheel drive,4,2170,5,226.0,3950,18.0,35.4

In [90]:
asia_weight_year = df_asia[['vehicle_weight', 'model_year']]

In [91]:
asia_weight_year.head(7)

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007
16            4750        2021
22            4450        2019

In [108]:
import numpy as np
X = np.array(asia_weight_year.head(7))
X

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

In [121]:
X_transpose = X.T
X_transpose

array([[4240, 4310, 4230, 4420, 3950, 4750, 4450],
       [1996, 1992, 1997, 1978, 2007, 2021, 2019]])

In [122]:
XTX = X_transpose.dot(X)
XTX

array([[131950500,  60750580],
       [ 60750580,  28041424]])

In [123]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 2.96830537e-06, -6.43071025e-06],
       [-6.43071025e-06,  1.39675281e-05]])

In [124]:
y = [1100, 1300, 800, 900, 1000, 1100, 1200]

Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.

In [126]:
w = (XTX_inv.dot(X_transpose)).dot(y)
w

array([0.13644777, 0.2327492 ])

In [127]:
w.sum()

np.float64(0.36919696904925486)